### ISSUE TITLE
Tools for blocks broken with this mod

### ISSUE THREAD

**Issue by lospejos** [PixelPacker/FishingAquatica#1]
Hi!

Have `Minceraft` local on `Fabric 1.19.2` with mods:

`fabric-api-0.62.0+1.19.2.jar`
`modmenu-4.0.6.jar`
`wthit-fabric-5.12.0.jar`
`can-i-mine-this-block-1.3.0.jar`
`fabrishot-1.8.0.jar`
`badpackets-fabric-0.2.0.jar`
`cloth-config-8.2.88-fabric.jar`

Everything works just fine, every block has proper preferred tool to mine:

Tree:
![image](https://user-images.githubusercontent.com/4608475/195099026-dbad2ea5-7306-4647-93b0-7ecac3fce2e8.png)

Stone:
![image](https://user-images.githubusercontent.com/4608475/195099128-dc14ca67-8488-43b7-92d9-7f1ef476d8ee.png)

Dirt:
![image](https://user-images.githubusercontent.com/4608475/195099284-99f252eb-d188-4ffe-9f8b-7a1df690845a.png)

and so on. 

**After installing mod** `FishingRework-0.2.2.jar`, only blocks with tools `Shovel` reported properly, other blocks do not have preferred tool. Mining of these block is slow (just like a hand without any tool), and after mining no block is mined.

Tree:
![image](https://user-images.githubusercontent.com/4608475/195099563-193f8ffb-d81d-4ceb-9618-ccc8da0ea44e.png)

Stone:
![image](https://user-images.githubusercontent.com/4608475/195099719-eea2b94d-d378-48b9-a4e2-d45e55f88e30.png)

Dirt:
![image](https://user-images.githubusercontent.com/4608475/195099865-6fb122ea-db6e-4b7b-933f-15ae2017e067.png)

Log file also contains:

```
[16:03:38] [Worker-Main-26/ERROR]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: fishingrework:mob_resource_crate (from Fishing Aquatica)
[16:03:38] [Worker-Main-26/ERROR]: Couldn't load tag minecraft:mineable/axe as it is missing following references: fishingrework:plant_crate (from Fishing Aquatica)
```

Please assist. Thanks.

**Comment by Leo40Git** [comment]
The actual issue is the aforementioned missing references in the `mineable` tags - this causes the _entire_ tag to not load (including vanilla entries), hence why oak logs and stone no longer have a preferred tool.

**Comment by Byte-Oracle** [comment]
Build has been uploaded to Github, Modrinth, and Curseforge (waiting approval)
Once again thanks for spotting that, guess that tells you what I do anytime with my own mod
