### ISSUE TITLE
Crash on server start up Minecraft 1.20.1 with Fabric Loader 0.15.3

### ISSUE THREAD

**Issue by 2el222** [PixelPacker/FishingAquatica#10]
[latest.log](https://github.com/PixelPacker/FishingAquatica/files/13820708/latest.log)

**Comment by Byte-Oracle** [comment]
This is likely due to a library being used in this version is now included in fabric loader.
I will update the 1.20.1 version when I get a chance. Thank you for the report!

**Comment by 2el222** [comment]
Thank you! Tested your mod out and really want it in my server! Will be waiting for the update!

**Comment by Byte-Oracle** [comment]
Resolved in https://github.com/PixelPacker/FishingAquatica/commit/e04032a9f13acc4fecffc5eeb8ffd2b49e09508c
Uploading updated versions to platforms now
