### ISSUE TITLE
Is Sword Fish acquirable in Survival?

### ISSUE THREAD

**Issue by ninjaeon** [PixelPacker/FishingAquatica#11]
If not, how would I go about adding it to the rare resources crate loot table, maybe 1 in 10000 chance?

**Comment by ninjaeon** [comment]
Assuming that it's not acquirable yet, I figured it might be possible to add it to the loot table with a datapack.

This is my first try at making a datapack, but I made a zip with \data\fishingrework\loot_tables\blocks\rare_resource_crate.json with the following in an attempt at this:

```
{
  "type": "minecraft:block",
  "pools": [
	{
	  "rolls": 3,
	  "entries": [
		{
		  "type": "minecraft:item",
		  "weight": 1,
		  "name": "minecraft:emerald_block"
		},
		{
		  "type": "minecraft:item",
		  "weight": 1,
		  "name": "minecraft:lapis_block"
		},
		{
		  "type": "minecraft:item",
		  "weight": 2,
		  "name": "minecraft:gold_block"
		},
		{
		  "type": "minecraft:item",
		  "weight": 2,
		  "name": "minecraft:iron_block"
		},
		{
		  "type": "minecraft:item",
		  "weight": 4,
		  "name": "minecraft:diamond"
		},
		{
		  "type": "minecraft:item",
		  "weight": 2,
		  "name": "minecraft:blaze_rod"
		},
		{
		  "type": "minecraft:item",
		  "weight": 3,
		  "name": "minecraft:ender_pearl"
		},
		{
		  "type": "minecraft:item",
		  "weight": 6,
		  "name": "minecraft:emerald"
		},
		{
		  "type": "minecraft:item",
		  "weight": 4,
		  "name": "minecraft:experience_bottle"
		},
		{
		  "type": "minecraft:item",
		  "weight": 0.0075,
		  "name": "fishingrework:sword_fish"
		}
	  ],
	  "conditions": [
		{
		  "condition": "minecraft:survives_explosion"
		}
	  ]
	}
  ]
}
```

**Comment by Byte-Oracle** [comment]
Hey! That is correct that the swordfish is currently unobtainable as I wasn't sure where to slot it into the crates balance wise. 
As for inserting datapacks I believe the way you have done it is correct but I sadly don't have much experience with it personally. 
I would highly recommend trying to set the weight of the Swordfish to 1 instead and bump all other items up by one as such low odds would likely make it never obtainable.
