### ISSUE TITLE
Not crafting

### ISSUE THREAD

**Issue by Ihaeklag** [PixelPacker/FishingAquatica#13]
I have a lot of mods installed including this one, but when i try to craft an iron fishing rod like you do with normal ones it doesn't work. How do I fix this? fabric 0.15.7, 1.20.1

**Comment by Byte-Oracle** [comment]
When using jei are you able to see the crafting recipe?

**Comment by Ihaeklag** [comment]
No i'm not.

**Comment by Byte-Oracle** [comment]
Hmm, could you let me know what version of the mod you have installed. I should be able to verify if this is a compatibility issue with other mods or not on my end.

**Comment by Ihaeklag** [comment]
the most recent one (1.20.1-0.2.8.1) release 1/3/2024

**Comment by Byte-Oracle** [comment]
I just checked in game and it appears to work good for me. Could you let me know what mods you have installed and also double check you are using the same recipe as the wiki? https://github.com/PixelPacker/FishingAquatica/wiki/Fishing-Rods

**Comment by Ihaeklag** [comment]
[copy.zip](https://github.com/PixelPacker/FishingAquatica/files/15154020/copy.zip)

this is my mod pack i'm using now

**Comment by Byte-Oracle** [comment]
After checking the modpack you sent it seems to work no issue on my end.
<img width="557" alt="javaw_J5Pa27o2L3" src="https://github.com/PixelPacker/FishingAquatica/assets/9503337/3a35fd91-ef02-4604-bbb5-15722822138c">
