### ISSUE TITLE
Fabric 1.20: Invalid or unsupported recipe type 'minecraft:smithing'

### ISSUE THREAD

**Issue by jshipley** [PixelPacker/FishingAquatica#5]
In minecraft 1.20, the minecraft:smithing recipe type doesn't exist anymore, so there's currently no way to make the netherite fishing rod.

It should use the new minecraft:recipe_smithing_transform recipe which uses a smithing template along with the diamond tool and netherite ingot to create a netherite tool

**Comment by Byte-Oracle** [comment]
Thanks a ton, I knew I was gonna end up missing one thing.
I'll get this fixed asap

**Comment by Byte-Oracle** [comment]
Fixed. Builds uploading to sites

**Comment by Byte-Oracle** [comment]
https://github.com/PixelPacker/FishingAquatica/releases/tag/v1.20-0.2.6.1
